import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import Navbar from "./Components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
            <body>
                <div className="layout">
                    <Sidebar />

                    <div className="main-content">
                        {/* <Navbar /> */}

                        <main className="page-content">
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </html>
  );
}
